const recipeData = [
  {
    "id": 1,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654808608/coffeepic_i2rbhi.webp",
    "recipeTitle": "Bulletproof Coffee",
    "servings": "4 servings",
    "ingredients": ["1 cup hot coffee freshly brewed", "2 tbsp unsalted butter", "1 tbsp MCT or Coconut oil"],
    "directions": ["Combine all ingredients in a blender.", "Blend until smooth and frothy.", "Serve immediately."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 334, Protein: 1g, Complex carbs: 0g, Misc. carbs: 0g, Fat: 38g",
    "mealType": "Breakfast"
  },
  {
    "id": 2,
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Pizza-Noodle-Bake_EXPS_GHBZ18_40275_C08_30_3b-8.jpg?fit=696,696",
    "recipeTitle": "Classic Turkey Bacon and Eggs",
    "servings": "18 servings",
    "ingredients": ["8 eggs", "5 oz turkey bacon, slices", "Cherry tomatoes (optional)", "Fresh parsley (optional)"],
    "directions": ["Fry the bacon in a pan on medium high heat until crispy. Put aside on a plate. Leave the rendered fat in the pan.", "Use the same pan to fry the eggs. Place it over medium heat and crack your eggs into the bacon grease (you can also crack them into a measuring cup and carefully pour into the pan to avoid splattering of hot grease).", "Cook the eggs any way you like them. For sunny side up: leave the eggs to fry on one side and cover the pan with a lid to make sure they get cooked on top. For eggs cooked over easy: flip the eggs over after a few minutes and cook for another minute. Cut the cherry tomatoes in half and fry them at the same time.", "Salt and pepper to taste."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 272, Protein: 15g, Complex carbs: 0g, Misc. carbs: 4g, Fat: 22g",
    "mealType": "Breakfast"
  },
  {
    "id": 3,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654809167/BreakfastPie_loqysu.jpg",
    "recipeTitle": "Easy Crockpot Breakfast Pie",
    "servings": "5 servings",
    "ingredients": ["8 eggs, whisked", "1 sweet potato or yam, shredded", "1lb organic ground turkey or ground bison, broken up", "1 yellow onion, diced", "1 tablespoon garlic powder", "2 tsp. dried basil", "Salt and pepper, to taste", "Any extra veggies you want to put in there: peppers, squash, broccoli, tomatoes, etc."],
    "directions": ["Greased crockpot with a bit of coconut oil to make sure none of the egg sticks to it.", "Shred your sweet potato using a food processor or grater.", "Add all ingredients to your crockpot and use a spoon to mix well.", "Place on low for 6-8 hours.", "Slice it like a pie and serve!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 247, Protein: 33g, Complex carbs: 7g, Veggie carbs: 2.4g, Fat: 7.2g"
  },
  {
    "id": 4,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654809282/EggplantFrenchToast_jljkoq.jpg",
    "recipeTitle": "Eggplant French Toast",
    "servings": "Depends on size of eggplant",
    "ingredients": ["1 eggplant, peeled & sliced to 1⁄4 inch thick", "3 egg whites", "1 tsp vanilla bean paste", "1⁄2 tsp all spice"],
    "directions": ["Beat eggs, vanilla, and spices", "Slice eggplant in ¼ inch thick slices.", "Dip eggplant in egg mixture, then cook in covered pan over medium heat until each side is golden brown.", "Serve with toppings (optional)", "Walden Farms SF Maple Syrup"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "No details available",
    "mealType": "Breakfast"
  },
  {
    "id": 5,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654809453/SavoryBreakfastCasserole_xjda1o.jpg",
    "recipeTitle": "Savory Breakfast Casserole",
    "servings": "6 servings",
    "ingredients": ["12 eggs, whisked", "1 lb organic ground turkey or ground bison", "1 sweet potato, shredded", "½ yellow onion, diced", "2 tablespoons hot sauce or Sirach", "1 tsp. garlic powder", "1 tsp. onion powder", "1 tsp. salt", "1 tsp. pepper"],
    "directions": ["Preheat your oven to 375 degrees.", "Add ground turkey to a hot skillet and let cook until it begins to crumble. 3. While the meat is cooking, dice up your onion and shred your sweet potato with a grater  or food processor.", "Beat eggs in a large bowl.", "Add the cooked meat, onion, and sweet potato to the bowl with the whisked eggs. Then  add the rest of your ingredients and mix all together.", "Grease an 8×8 or 9×9 glass dish and add your egg mixture to it.", "Cook for 25-30 minutes until a toothpick comes out clean in the middle.", "Let sit for 10 minutes before serving."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 320, Protein: 31.3g, Complex carbs: 5.8g, Misc. carbs: 2g, Fat: 15.6g",
    "mealType": "Breakfast"
  },
  {
    "id": 6,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654810126/healthy-breakfast-casserole-1_xf74cj.jpg",
    "recipeTitle": "Spinach, Turkey & Egg Breakfast Skillet",
    "servings": "2 servings",
    "ingredients": ["4 cups organic baby spinach", "4 organic eggs", "2 tbsp. coconut oil", "Salt and Pepper to taste", "8 oz. organic ground turkey (or chicken)", "Scallions (optional)", "Mushrooms (optional)"],
    "directions": ["Preheat skillet with coconut oil.", "Beat eggs in a mixing bowl and add salt and pepper and add to skillet.", "Add ground turkey and mushrooms", "When eggs are almost done, add spinach and stir until wilted.", "Enjoy!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 417, Protein: 48g, Veggie carbs: 8g, Fat: 22.5g",
    "mealType": "Breakfast"
  },
  {
    "id": 7,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654810415/MushroomOmelet_ynxthy.webp",
    "recipeTitle": "Mushroom Omelet",
    "servings": "1 serving",
    "ingredients": ["3 eggs", "1 oz butter, for frying", "1 oz organic shredded cheese", "1/5 yellow onion", "3 mushrooms", "Salt and pepper"],
    "directions": ["Crack the eggs into a mixing bowl with a pinch of salt and pepper. Whisk  the eggs with a fork until smooth and frothy.", "Add salt and spices to taste.", "Melt butter in a frying pan. Once the butter has melted, pour in the egg mixture.", "When the omelet begins to cook and get firm, but still has a little raw egg on top,  sprinkle cheese, mushrooms, and onion on top (optional).", "Using a spatula, carefully ease around the edges of the omelet, and then fold it over in  half. When it starts to turn golden brown, underneath, remove the pan from the heat  and slide the omelet on to a plate.", "TIP! Serve with a green salad and vinaigrette dressing on the side. Yummy!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 510, Protein: 25g, Complex carbs: 0g, Veggie carbs: 4.7g, Misc carbs: 2g, Fat: 43g",
    "mealType": "Breakfast"
  },
  {
    "id": 8,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654810541/Cauliflower-Hash-Browns-Recipe_lvoctz.jpg",
    "recipeTitle": "Cauliflower Hash Browns",
    "servings": "4 servings",
    "ingredients": ["15 oz cauliflower", "3 eggs", "1/2 yellow onion, grated", "1 tsp salt", "2 pinches pepper", "4 oz butter, for frying"],
    "directions": ["Rinse, trim and grate the cauliflower using a food processor or grater.", "Add cauliflower to a large bowl. Add remaining ingredients and mix. Set aside for 5-10 minutes.", "Melt a generous amount of butter or oil on medium heat in a large skillet. The cooking  process will go quicker if you plan to have room for 3-4 pancakes (about 3-4 inches  each) at a time. Use the oven on low heat to keep the first batches of pancakes warm  while you make the others.", "Place scoops of the grated cauliflower mixture in the frying pan and flatten then  carefully until they measure about 3-3 inches in diameter."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 278, Protein: 7g, Complex carbs: 0g, Veggie carbs: 1g, Misc carbs: 1g, Fat: 26g",
    "mealType": "Breakfast"
  },
  {
    "id": 9,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654810665/MR_Vegetable-Fritatta177_qfl0cv.jpg",
    "recipeTitle": "Vegetable Frittata",
    "servings": "4 servings",
    "ingredients": ["1 1/2 tablespoons olive oil", "1 cup diced zucchini", "1/2 cup chopped red bell pepper", "1/3 cup chopped onion", "1 tablespoon chopped fresh thyme", "1/2 tsp. salt, divided", "1/4 tsp. freshly ground black pepper, divided", "2 garlic cloves, minced", "1/2 cup chopped seeded tomato", "9 large eggs"],
    "directions": ["Heat olive oil in a 10-inch nonstick broiler-proof skillet over medium heat. Add zucchini,  bell pepper, onion, thyme, 1/4 tsp. salt, 1/8 tsp. black pepper, and garlic.", "Cover and cook 7 minutes or until vegetables are tender, stirring occasionally. Stir in  tomato. Cook, uncovered, for 5 minutes or until liquid evaporates.", "Combine eggs, remaining 1/4 tsp. salt, and remaining 1/8 tsp. black pepper in a medium  bowl; stir with a whisk until frothy. Pour egg mixture into pan over vegetables, stirring  gently. Cover, reduce heat, and cook 15 minutes or until almost set in the center.", "Preheat broiler.", "Broil frittata 3 minutes or until set. Invert onto a serving platter; cut into 8 wedges."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 254, Protein: 15g, Veggie carbs: 11.5g, Fat: 14.5g",
    "mealType": "Breakfast"
  },
  {
    "id": 10,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654810809/mushroom-frittata-square-2019-500x500_ourksh.jpg",
    "recipeTitle": "Mushroom Frittata",
    "servings": "4 servings",
    "ingredients": ["2 - 3 garlic cloves (thinly sliced)", "2 tablespoon avocado oil", "1 onion chopped or Leeks - optional", "¼ teaspoon crushed red pepper (Optional)", "Pinch of Salt", "Pinch of Pepper", "6-8 large eggs (Large) I normally only use 5 eggs", "½ cup of almond milk or warm water (depends on how large your eggs are)"],
    "directions": ["Blanch mushrooms and let cool.", "In nonstick pan, add the garlic, avocado oil, salt, pepper and crushed red pepper.", "Cook on Medium heat only.", "Allow to onions to become translucent - optional.", "Add the precooked mushrooms.", "Mix in nonstick pan well.", "In a bowl add your eggs and beat with a fork", "Pour the egg mixture evenly over the mushrooms.", "Once the eggs have browned on one side, flip the frittata with the use of a dinner plate  over the sink. (the other option is to bake the frittata in the oven at 350 degrees 10. Cook on both sides, slice like a pie, and serve with your favorite salad, or Cauliflower  Rice, or on top of your 90 second bread."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "No details available",
    "mealType": "Breakfast"
  },
  {
    "id": 11,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654811036/keto-waffles-stacked-on-a-plate-with-butter_hxyzri.jpg",
    "recipeTitle": "Keto Waffles",
    "servings": "1 waffle",
    "ingredients": ["5 eggs", "4 tbsp coconut flour", "4 tbsp granulated stevia or sweetener of choice", "1 tsp baking powder", "2 tsp vanilla", "3 tbsp full fat coconut milk", "1 stick plus 1 tbsp butter (melted)", "Lakanto Sugar Free Maple Syrup"],
    "directions": ["FIRST BOWL: First whisk the egg whites until firm and form stiff peaks.", "SECOND BOWL: Mix the egg yolks, coconut flour, sweetener, and baking powder.", "Add the melted butter slowly, mixing to ensure it is a smooth consistency.", "Add the milk and vanilla, mix well.", "Gently fold spoons of the whisked egg whites into the yolk mixture. Try to keep  as much of the air and fluffiness as possible.", "Place enough of the waffle mixture into the warm waffle maker to make one  waffle. Cook until golden.", "Repeat until all the mixture has been used.", "Top with Lakanto Sugar Free Maple Syrup"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 277, Protein: 6.8g, Veggie carbs: 0g, Misc carbs: 4.6g, Sugar: 1.2g, Fat: 25.6g",
    "mealType": "Breakfast"
  },
  {
    "id": 12,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654811287/pics-Vegetarian-Frittata-feature_duvqwb.jpg",
    "recipeTitle": "Egg & Veggie Frittata",
    "servings": "4 servings",
    "ingredients": ["6 eggs & 4 egg whites", "4 garlic cloves, minced", "2 cups baby spinach", "1/4 cup almond milk", "2 Tbsp. coconut oil", "1 medium onion", "1/3 cup mushrooms", "2 Tbsp. Cilantro, chopped", "Salt and Pepper to taste"],
    "directions": ["Preheat oven to 425 degrees.", "Take a bowl and whisk the eggs and almond milk together.", "Preheat medium skillet on medium with coconut oil.", "Add spinach, garlic, onions, mushrooms, and cilantro into the skillet.", "Cook for 5-6 min until tender.", "Add egg mixture into the skillet and set to low heat.", "Cook for 8-10 min and remove.", "Place in oven for 15-18 minutes until done."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 253, Protein: 16g, Veggie carbs: 10g, Misc carbs: 4.25g, Fat: 14.5g",
    "mealType": "Breakfast"
  },
  {
    "id": 13,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654812625/Screen_Shot_2022-06-09_at_4.09.49_PM_uyvzo4.png",
    "recipeTitle": "Breakfast Indian Dish",
    "servings": "4 servings",
    "ingredients": ["7 oz cauliflower", "2 tbsp ghee or butter or coconut oil", "1 tbsp yellow mustard seeds", "1 tbsp cumin seeds", "5 curry leaves", "1 ¾ oz red onions, chopped Pink fresh ginger", "1 green chili pepper (optional)", "2/3 oz salted peanuts or use 1 tbsp powdered peanut butter (optional)", "Fresh cilantro"],
    "directions": ["Break apart the cauliflower into large florets, transfer the cauliflower into a food  processor and pulse until completely broken down into rice sized pieces.", "Heat ghee in a wok or frying pan and add the mustard seeds and cumin.", "Once they start to sizzle, add chopped onion, curry leaves, ginger, green chili pepper and  peanuts.", "Fry on low-medium heat until the onions get translucent, Salt to taste.", "Add the rice sized cauliflower, combine well and fry for a few minutes.", "Add some water so it almost covers the mixture. Cook for 10 minutes with the lid on.", "Keep checking and stirring every few minutes to ensure that nothing sticks to the  bottom of the pan.", "Cook until the water evaporates. Finish with adding the fresh cilantro."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 252, Protein: 7g, Complex carbs: 8g, Misc carbs: 4g, Fat: 21g",
    "mealType": "Breakfast"
  },
  {
    "id": 14,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654812718/hungry-girl-healthy-egg-mugg-classic-recipe-20181109-1352-21642-4871_l6qjl3.jpg",
    "recipeTitle": "Mug Scrambled Eggs",
    "servings": "1 serving",
    "ingredients": ["2 eggs", "2 tbsp coconut milk (with fat)", "1 tbsp butter", "Salt and pepper"],
    "directions": ["Grease a large cup or mug with soft butter. Whisk together eggs and heavy whipping cream. Fill cup to a maximum of two-thirds, as the eggs will gain volume  while cooking.", "Add a pinch of salt and freshly ground black pepper or cayenne.", "Microwave at maximum power for 1-2 minutes. Stir and microwave for another  minute. Keep in mind that eggs keep cooking after being removed from the heat, so  do not overdo it.", "Remove and add some butter. Let cook for a minute.", "Tip! Serve scrambled eggs with finely chopped chives, tuna, and slices of bell pepper to enjoy a  nutritious quick meal. You can exclude the cream if you want to avoid dairy products."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 328, Protein: 12g, Complex carbs: 0g, Misc carbs: 5g, Fat: 31g",
    "mealType": "Breakfast"
  },
  {
    "id": 15, 
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654812890/keto-crepes-featured-2021_iazwpx.jpg",
    "recipeTitle": "Coconut Flour Crepes",
    "servings": "4 servings",
    "ingredients": ["4 Eggs", "¼ cup Almond Flour", "1 teaspoon vanilla essence ", "¼ teaspoon ground cinnamon", "1 tablespoon Coconut oil to grease the crepe pan", "1-2 tablespoons of Monk Fruit Sugar"],
    "directions": ["In a medium bowl whisk the eggs, ground  almond, vanilla extract, ground cinnamon and sugar-free crystal sweetener of your  choice. Whisk until all the ingredients are perfectly combined and no lumps form.", "Warm a crepe pan of 9 inches diameter or a nonstick frying pan on medium heat and  use an absorbent paper to rub the coconut oil on the pan and grease the pan.", "Scoop the crepe batter into the frying pan and tilt the pan in a circular motion to ensure  that the batter coasts the surface evenly. The thickness of the crepes will depend on  how much batter you use for each. Usually, ¼ cup is what you need to make a 10-inch crepe", "Cook the crepe until the sides start to crisp  up and lift off easily from the frying pan. It  should take about 2 minutes each, over  medium heat.", "Loosen with a spatula and flip over to cook  the other side. Both sides should be lightly  brown, and the crepes should be crispy on  the sides and softer in the middle.", "Repeat for the next crepes.", "To service fill each crepe with the whipped  coconut cream, fold in a triangle, and top  with the fruits of your choice fresh berries,  spicy plum jam, etc.", "Can store in the fridge up to two days.", "Low Carb sweet filling ideas: whipped  coconut cream sweetened with stevia,  berries, sugar-free jam, yogurt, sugar-free  melted chocolate, desiccated coconut,  unsweetened cocoa powder, nut butter,  seed butter or even coconut butter. Savory Filling: these crepes make a  delicious savory meal as well. Simply do not  add the vanilla and cinnamon in the batter,  add ¼ teaspoon salt instead. After you cook  the crepes bring back to the pan, add a  handful of vegan grated cheese and some  turkey bacon. Grilled vegetables fold the  crepes in half and return to the pan for a  few minutes until the cheese is melted.  Favorite combos are vegan cheddar and  turkey bacon and fried onions or vegan  cream cheese and spinach."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 127, Protein: 7.6g, Misc carbs: 4.6g, Sugar: .5g, Fat: 8.5g",
    "mealType": "Breakfast"
  },
  {
    "id": 16, 
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654813092/Gluten-Free-Blueberry-Pancakes-6_o5oc41.jpg",
    "recipeTitle": "Blueberry Pancakes",
    "servings": "2 servings",
    "ingredients": ["6 eggs", "4 oz nondairy vegan cream cheese", "3 oz melted butter", "2/3 cup almond flour", "2/3 cup oat fiber", "2 tsp baking powder", "½ lemon zest", "1 pinch salt", "3 oz fresh blueberries", "WF Blueberry Syrup"],
    "directions": ["In a bowl, whisk together eggs, cream cheese, and melted butter.", "Mix the rest of the ingredients separately, except blueberries, and then pour into the  egg mixture, combine well until you get a smooth batter. Let rest for a few minutes.", "Fry the pancakes over medium heat in a small nonstick pan or cast-iron pan. Use  around 0.3 cup batter per pancake.", "Fry for a few minutes and gently add some blueberries, without pressing them down too  hard. Flip and fry for a few more minutes", "Serve with whipped cream or the WF blueberry syrup."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 478, Protein: 15g, Complex carbs: 8g, Misc carbs: 5g, Fat: 44g",
    "mealType": "Breakfast"
  },
  {
    "id": 17,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654813315/healthy-strawberry-milkshake-2_m3kkek.jpg",
    "recipeTitle": "Strawberry Smoothie",
    "servings": "1 serving",
    "ingredients": ["14 oz unsweetened coconut milk", "1 cup fresh strawberries", "1 tbs lime juice", "1⁄2 tsp vanilla extract"],
    "directions": ["Place all ingredients in a blender and blend until smooth. Using canned coconut mile (drain off the liquid) makes it creamier, more satisfying smoothie.", "Add lime juice to taste.", "Tip! If you want a more filling smoothie, go ahead, and add 1 tbsp of coconut oil or any other healthy oil."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 418, Protein: 5g, Complex carbs: 0g, Misc carbs: 10g, Fat: 42g"
  },
  {
    "id": 18, 
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654813478/key-lime-pie-smoothie.jpeg_hn7je8.jpg",
    "recipeTitle": "Key Lime Pie Smoothie",
    "servings": "1 serving",
    "ingredients": ["1 cup full fat organic unsweetened coconut milk", "1 ripe avocado", "1 large handful of spinach or collard greens", "1⁄4 cup-soaked cashews (optional)", "Juice of 1 lime (2 tbsp)", "1 scoop of plant based protein powder (optional) I used Sun warrior Plant Based Vanilla", "5-10 drops of vanilla stevia (optional to taste)"],
    "directions": ["Gather all ingredients and prepare them.", "Put all ingredients in blender and blend. Blendtec or Vitamix works really well if you have one.", "Blend until smooth and creamy.", "Serve and enjoy."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Nutritional info does not include the optional ingredients. Calories: 415, Protein: 14g, Complex carbs: 0g, Misc carbs: 12g, Fat: 37g",
    "mealType": "Breakfast"
  },
  {
    "id": 19, 
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654813722/Vegan-Pumpkin-Spice-Latte-1098_kctadc.webp",
    "recipeTitle": "Pumpkin Spice Morning Latte",
    "servings": "1 serving",
    "ingredients": ["8 oz. brewed coffee", "3⁄4 cup nondairy milk of choice (Almond or Coconut unflavored)", "2 tbsp. canned pumpkin", "1 tbsp. coconut butter", "1 tsp pumpkin pie spice", "10 vanilla stevia drops (optional)", "2 tbsp. chilled coconut cream (optional)"],
    "directions": ["Add coffee and stevia to a small pot and whisk until very warm (about 3 minutes).", "Add to small blender, and process until frothy, if desired, or pour straight into a mug.", "Top with coconut cream and sprinkle with additional cinnamon or pumpkin pie spice.", "You can use instant coffee with 8oz water, if desired.", "To make coconut cream, simply refrigerate a can of coconut cream or coconut milk in the fridge until hard. Once chilled, the hard part on top is the coconut cream. Spoon off the top and add to your latte, if desired."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 239, Protein: 3g, Complex carbs: 0g, Misc carbs: 8g, Fat: 22g",
    "mealType": "Breakfast"
  },
  {
    "id": 20,
     "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654813831/scrambledEggsChocolatePudding_bldvul.jpg",
    "recipeTitle": "Scrambled Egg Chocolate Pudding",
    "servings": "4 servings",
    "ingredients": ["8 large eggs (cooked scrambled)", "1 cup unsweetened almond milk or milk of choice", "1/2 cup Swerve confectioners", "1/4 cup unsweetened cocoa powder", "1/2 tsp vanilla extract", "1/2 tsp cinnamon", "pinch salt"],
    "directions": ["Place your scrambled eggs into a high powered blender with the rest of the ingredients. Blend until completely smooth in texture. Taste and adjust your sweetener if needed.", "Pour batter evenly into 4 serving glasses and refrigerate until set, about an hour.", "Store in the fridge covered, for up to 4 days."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 163, Protein: 13g, Complex carbs: 5g, Sugar: 1g, Fat: 11g",
    "mealType": "Breakfast"
  },
  {
    "id": 21,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654817090/Vegan-crack-slaw-recipe_poujre.webp",
    "recipeTitle": "Keto Crack Slaw",
    "servings": "6 servings",
    "ingredients": ["4 cups shredded green cabbage", "1⁄2 cup macadamia nuts, chopped", "1 tsp chili pasted, kimchi pasted (vegan), or Sriracha", "1 tsp vinegar", "2 tbsp. tamari or liquid aminos", "1 tbsp. coconut oil or almond butter", "2 cloves garlic", "Sesame seeds and green onion to garnish (if desired)"],
    "directions": ["Toss cabbage in a pan with the tamari, vinegar, coconut oil and chili pasted/kimchi paste/Sriracha on medium low heat.", "Add in minced garlic.", "Cover and let sit for about 5 minutes, until the cabbage starts to soften.", "Stir everything in the pan so that it is thoroughly combined. Add in nuts.", "Cook for another 5 or so minutes, until the nuts soften from absorbing some of the extra liquid in the pan.", "Serve, garnish, and enjoy!!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 58.5, Protein: 1.3g, Veggie carbs: 4.2g, Misc. carbs: 3.5g, Fat: 4.3g",
    "mealType": "Salads, Sauces & Sides"
  },
  {
    "id": 22,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654817462/Jicama-salad_f3z3pf.jpg",
    "recipeTitle": "Jicama Salad",
    "servings": "6 servings",
    "ingredients": ["2 medium jicamas", "1 bell pepper (red, yellow, or orange) chopped", "1 Citrus Avocado Dressing",  "Handful of Cilantro"],
    "directions": ["Peel jicama, then spiralizer to make jicama noodles.", "Toss with bell pepper and Citrus Avocado dressing. Garnish with cilantro and serve."],
    "toppingTitle": "Citrus Avocado Dressing", 
    "toppingIngredients": ["1⁄2 avocado, peeled and seeded", "1⁄2 cup fresh squeezed OJ", "Juice of 1 lime", "1 1⁄2 tbsp Lakanto SF maple syrup", "1⁄4 cup fresh cilantro", "1⁄2 small jalapeno, minced (optional)", "2/3 cup olive oil", "Fresh ground black pepper", "Pinch salt"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 297, Protein: 3g, Veggie carbs: 20g, Misc. carbs: 13g, Fat: 22g",
    "mealType": ["Salads, Sauces & Sides"]
  },
  {
    "id": 23,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654817770/Black-Bean-Salad_jzdlf4.jpg",
    "recipeTitle": "Black Bean and Tomato Salad",
    "servings": "6 servings",
    "ingredients": ["3 tablespoons coconut oil", "1 onion, diced", "1 tablespoon kosher salt", "2 1/2 tsp. smoked paprika", "1/2 tsp. cayenne pepper, optional", "2 cups frozen and thawed corn kernels (optional and ONLY IF ORGANIC)", "1 dried bay leaf", "3/4 cup chicken broth", "2 (15-ounce) cans black beans, rinsed and drained", "2 tomatoes, chopped", "6 ounces jicama, peeled and diced into 1/4-inch pieces (about 1 cup)", "1/4 cup chopped fresh cilantro leaves"],
    "directions": ["In a large skillet, heat the oil over medium-high heat. Add the onion, salt, smoked paprika, and cayenne pepper, if using. Cook for 6 to 8 minutes until soft. Add the corn kernels and bay leaf.", "Cook, stirring constantly, for 2 minutes. Add the broth and black beans. Bring the mixture to a boil, reduce the heat and simmer for 4 minutes.", "Add the tomatoes and jicama and stir until warmed through, about 1 minute. Remove the pan from the heat.", "Remove the bay leaf and put the salad in a serving bowl. Pour the dressing over the salad and mix well. Season with salt and pepper, to taste.", "Garnish with chopped cilantro and serve warm or at room temperature."],
    "toppingTitle": "Dressing", 
    "toppingIngredients": ["2 tablespoons lemon juice", "2 tablespoons lime juice", "2 tablespoons Lakanto SF maple syrup", "2 tablespoons lemon zest", "2 tablespoons lime zest", "1/4 cup extra-virgin olive oil", "Kosher salt and freshly ground black pepper"],
    "toppingDirections": ["In a small bowl, combine the lemon juice, lime juice, agave nectar (or maple syrup, if using), lemon zest, and lime zest. Whisk in the olive oil until the mixture is smooth. Season with salt and pepper, to taste."],
    "nutritionDetails": "Calories: 313.5, Protein: 7.5g, Complex carbs: 17.5g, Veggie carbs: 18g, Misc. carbs: .1g, Fat: 16.7g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 24,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654817876/The-Best-Thai-Chicken-Mason-Jar-Salad-with-Peanut-Dressing-web-6_opyroq.jpg",
    "recipeTitle": "Salad in a Jar",
    "servings": "1 serving",
    "ingredients": ["4 oz. smoked salmon or rotisserie chicken (or protein of your choice)", "1/6 oz. leafy greens", "1/6 oz. cherry tomatoes", "1/6 oz. red bell peppers", "1⁄2 scallion", "4 tbsp. Primal Kitchen mayonnaise or any Primal Kitchen Salad Dressing"],
    "directions": ["Shred or chop vegetables of your choice. First, put dark leafy greens such as spinach or arugula at the bottom of the jar. Iceberg lettuce or romaine works too. Green and red cabbage gives a fresh crunch. Chopped broccoli or cauliflower also works great.", "Add sliced onions, shredded carrot, avocado different bell peppers and tomato in layers.", "We have chosen to top our salad with salmon, but you can use your own favorite protein, boiled eggs, or canned tuna. Olives, nuts, and seeds are great flavorful additions.", "To feel satisfied, you may want to add a generous amount of olive oil or you can combine apple cider vinegar with some lemon stevia for dressing."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 499, Protein: 35g, Complex carbs: 25.8g, Veggie carbs: 29g, Misc. carbs: 4g, Fat: 25g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 25,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654818079/CaulRiceCups.jpeg_j2hkh2.jpg",
    "recipeTitle": "Cauliflower Rice Lettuce Cups with Sriracha Peanut Sauce",
    "servings": "6 servings",
    "ingredients": ["1 tablespoon coconut oil", "2 cloves garlic, minced", "5 green onions, sliced", "2 small red bell peppers, finely diced", "2 small green bell peppers, finely diced", "5 ounces shiitake mushrooms, chopped", "2 large carrots, shredded (about 2 cups)", "1 lime, juiced", "2 tablespoons Liquid Aminos", "1/2-3/4 tsp. salt", "1 head cauliflower, shredded", "Iceberg of Bibb lettuce, for serving", "Cilantro and chopped peanuts, for topping"],
    "directions": ["Melt the coconut oil in a large nonstick skillet. Add the garlic and cook for 30 seconds, then add the onions and cook for 3-4 minutes. Stir in the peppers, mushrooms, and carrots, and squeeze on the lime, soy sauce, and half the salt. Cook, stirring frequently, for 7 minutes.", "Pour in the shredded cauliflower and remaining salt (to taste), and cook for another 5 minutes, stirring frequently.", "For the sauce: Combine all sauce ingredients in a saucepan over medium heat. Bring to a boil, and boil for 3-5 minutes, until thickened.", "Serve the cauliflower mixture in iceberg or Bibb lettuce cups, and drizzle on peanut sauce.", "I shredded my cauliflower in a food processor, which made it super quick and easy, but you can use a cheese grater if you don't have a food processor that shreds."],
    "toppingTitle": "Sriracha Peanut Sauce", 
    "toppingIngredients": ["1/2 cup natural salted peanut butter (organic)", "1 cup unsweetened coconut milk", "Few drops Stevia", "1/2 tsp. sea salt", "1 tablespoon brown rice vinegar", "1 tablespoon Sriracha"],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 268, Protein: 9.2g, Veggie carbs: 17.8g, Misc. carbs: 8g, Fat: 14.8g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 26,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654818260/Screen_Shot_2022-06-09_at_5.43.59_PM_kmawfd.png",
    "recipeTitle": "Chicken & Miracle Noodle Vegetable Salad with Sesame Peanut Dressing",
    "servings": "8 servings",
    "ingredients": ["8 oz. miracle noodles", "8 oz. shredded chicken", "2 cup Broccoli /Cauliflower Raw", "1 cup Select Edamame Shelled Soybeans", "0.5 pepper, Bell Pepper, Red (Large)", "0.5 pepper, Sweet Bell Pepper, Orange", "1 cup Bean Sprouts", "1⁄2 cup Peanuts, All types, dry-roasted, with salt", "2 T roasted sesame seeds"],
    "directions": ["Prepare miracle noodles according to package.", "In the last 2 minutes of cooking noodles, add broccoli/cauliflower florets.", "Drain and place both into a serving bowl.", "Toss in remaining ingredients.", "In a small bowl whisk dressing ingredients until smooth (I use a Magic Bullet to blend ingredients.)", "Toss gently into noodles and vegetables.", "Keep refrigerated. Eat hot or cold. Sprinkle PB2 if you want more peanut taste!"],
    "toppingTitle": "Dressing", 
    "toppingIngredients": ["1⁄2 c liquid Aminos", "3 T Peanut Oil", "Few drops Stevia", "3 T Oil Sesame Oil", "2 T Lime Juice", "1/2 cup Pb2 Peanut Butter Powder", "Stevia to sweeten"],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 127, Protein: 15g, Veggie carbs: 5.75g, Complex carbs: 3g, Fat: 10g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 27,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654818403/Chinese-Chicken_salad_lym81v.jpg",
    "recipeTitle": "Chinese Chicken Salad",
    "servings": "4 servings",
    "ingredients": ["4 Medium Chicken Breasts, cooked and cut into pieces", "4 large leaves Romaine lettuce", "3 celery stalks, chopped", "1 cup canned bean sprouts, drained", "1/2 cup Primal Kitchen French Dressing", "1/2 cup Primal Kitchen Avocado Mayo", "2 tablespoons coconut Aminos", "1/4 tsp. onion powder", "1/4 tsp. ground ginger", "1/4 tsp. salt", "1/4 tsp. pepper", "1/2 doz. green olives (optional)"],
    "directions": ["Mix all ingredients together.", "Place salad green on plate", "Top with all ingredients and top with olives"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 204.5, Protein: 35.5g, Veggie carbs: 3.5g,  Fat: 4g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 28,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654818633/Cucumber_Zucchini_Salad_BIG_peeg55.jpg",
    "recipeTitle": "Cucumber Zucchini Salad",
    "servings": "4 servings",
    "ingredients": ["2 cucumbers, thinly sliced", "2 zucchinis, thinly sliced", "1 small, sweet onion, thinly sliced (optional)", "1⁄3 cup vinegar", "1⁄4 cup Swerve or stevia", "1⁄2 tablespoon salt", "1 tsp. coarse black pepper, fresh cracked", "1 pinch red pepper flakes"],
    "directions": ["Arrange in alternate layers cucumber, zucchini & onions.", "Mix vinegar and sugar dissolved in 1/2 cup hot water add salt, pepper & crushed red pepper. Add a couple ice cubes to chill.", "Drain any water formed from cucumbers before adding the dressing.", "Allow vegetables to marinate in the dressing at least 1 hour before serving."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 45, Protein: .25g, Veggie carbs: 11.25g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 29,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654818797/guacamole-deviled-eggs_bqix34.jpg",
   "recipeTitle": "Deviled Avocado Eggs",
    "servings": "3 servings",
    "ingredients": ["1 large avocado", "3 egg yolks", "1 tsp. cilantro", "3 tsp. lime juice", "1 tbsp. red onion", "A pinch of salt and pepper", "Sprinkle of chili or paprika", "Primal Kitchen Avocado Mayo (optional)"],
    "directions": ["Mash 1 large avocado with 3 egg yolks.", "Add 1 tsp. cilantro, 3 tsp. lime juice, 1 tbsp. red onion, and a pinch of salt and pepper.", "Top with a sprinkle of chili or paprika.", "If you want a creamier center, mix yolk with mayo also. (optional idea)"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 135.3, Protein: 14g, Veggie carbs: 1g, Misc. carbs: 3.3g, Fat: 9.6g",
    "mealType": ["Salads, Sauces & Sides", "Sides"]
  },
  {
    "id": 30,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654818939/easy-ceviche_iwtajg.jpg",
    "recipeTitle": "Easy Ceviche",
    "servings": "6 servings",
    "ingredients": ["2 pounds of raw shrimp, cleaned, deveined, and cut into thirds (21-25 per pound)", "10 medium firm Roma tomatoes, diced", "5 mini cucumbers, peeled and diced", "1 medium red onion, diced", "1 bunch cilantro, finely chopped", "2-3 jalapenos, seeded and diced", "1/2 cup Lime Juice", "2 tablespoons of red chili flakes"],
    "directions": ["In a hot frying pan slightly toast red chili flakes for about 45 seconds.", "In a blender, blend together: lime juice, toasted red chili flakes, jalapenos, salt, and pepper to taste.", "Place cleaned and cut shrimp in a bowl add lime juice mixture cover and let sit for about 20 minutes or until shrimp turns pink.", "In a separate bowl combine cilantro, onion, tomatoes, and cucumber.", "When shrimp has turned pink drain about half of the lime juice from bowl and combine with the veggie mixture.", "Serve with fresh avocado; eat with chips or over a salad."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 231, Protein: 32.5g, Veggie carbs: 7.1g, Fat: 2.7g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 31,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654819118/GarlickyKale_2_SQ_xrp1qm.webp",
   "recipeTitle": "Garlic Kale Salad",
    "servings": "6 servings",
    "ingredients": ["2 bunches kale, chopped and de-stemmed", "4 cloves of garlic, pressed (or finely chopped)", "4 T tahini", "2 T coconut oil", "1 T apple cider vinegar", "1 T Bragg’s Liquid Aminos", "1 T Nutritional Yeast", "1 lemon, juiced", "Water"],
    "directions": ["Mix together all the ingredients, except Kale.", "Hand mix your garlic tahini dressing by hand with your washed and de-stemmed kale.This will also ensure your delicious dressing makes its way onto each and every piece of kale.", "Dressing your kale immediately before eating your raw kale salad is also a great option."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 146.3, Protein: 5g, Veggie carbs: 8.7g, Misc. Carbs: 3.25g, Fat: 10.7",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 32,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654819205/Best-Hummus_hdrwgy.webp",
    "recipeTitle": "Homemade Hummus Recipe",
    "servings": "1 serving",
    "ingredients": ["1 15 ounce can chickpeas drained", "1⁄4 cup tahini", "2 tablespoons lemon juice", "1 tablespoon garlic, minced", "1-2 tablespoons coconut oil", "Salt and pepper to taste"],
    "directions": ["To a food processor or blender, add the chickpeas, tahini, lemon juice, garlic, and salt and pepper. Pulse until well blended.", "Drizzle in olive oil until desired consistency is reached (hummus will firm up a little after refrigeration).", "Store in the refrigerator in an airtight container."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 740, Protein: 25g, Complex carbs: 13g, Misc. carbs: 40g, Fat: 52g",
    "mealType": ["Salads, Sauces & Sides", "Sauces"]
  },
  {
    "id": 33, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654819447/Thai-Noodle-Salad-with-Peanut-Sauce_mphl9c.webp",
   "recipeTitle": "Thai Noodle Salad",
    "servings": "6 servings",
    "ingredients": ["1 (6.75 ounce) package miracle noodles", "3 cloves garlic, minced", "1/3 cup seasoned rice vinegar", "3 tablespoons Bragg's Liquid Aminos", "1 tablespoon Asian chili paste", "1 tsp. Stevia", "1/4 tsp. salt", "4 green onions, chopped", "1/4 cup carrots, cut into thin matchsticks", "1/4 red peppers, julienned", "1/2 cup chopped fresh herbs (basil, mint, and cilantro)", "1 tsp. avocado oil", "1/4 cup Fresno chili peppers, cut into rings (optional)"],
    "directions": ["Prepare miracle noodles according to package.", "Combine garlic, rice vinegar, Aminos, chili paste, stevia, oil, and salt in a bowl.", "Stir in green onions, red peppers, carrots, basil, mint, and cilantro.", "Toss sauce and rice noodles. Allow to sit for 30 minutes to absorb flavors.", "Garnish with additional green onions.", "If using, top with grilled chicken and Fresno chiles."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 55, Protein: 2g, Veggie carbs: 3g, Misc. Carbs: 3g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 34,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654821218/Screen_Shot_2022-06-09_at_6.33.01_PM_s3a6fb.png",
   "recipeTitle": "Taco Lentil Salad",
    "servings": "4 servings",
    "ingredients": ["1 tbsp avocado oil", "2 cloves garlic, minced", "1⁄2 large onion, diced", "2 large bell peppers, diced", "1 cup dried lentils, rinsed", "2 1⁄2 water", "1 cup salsa", "1 (1 oz) packet non gmo taco seasoning", "1⁄4 cup cilantro"],
    "directions": ["Place the oil in skillet on medium heat.", "Sauté the garlic and onion for about 4 minutes.", "Add bell peppers and stir for 3 minutes.", "Add Lentils, water, salsa, and seasoning and stir.", "Bring to a boil, then reduce to medium heat and occasionally stir for the next 20-25 minutes until lentils are tender and slightly soft.", "Add more water, if needed. They should not be mush and all of the water should be absorbed.", "Serve over a bed of lettuce for a taco salad, in coconut wraps or lettuce wraps."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "No details available",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 35,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654821380/cucumber-tomato-salad_tbps4i.webp",
    "recipeTitle": "Tasty English Cucumber Salad",
    "servings": "6 servings",
    "ingredients": ["2-3 English cucumbers (chopped)", "3 ripe avocados", "4 roma tomatoes", "1⁄2 red onion", "1⁄4 cup chopped fresh cilantro", "Juice of 1 lemon", "Salt and black pepper to taste", "2 tbsp coconut oil"],
    "directions": ["Place sliced cucumber, tomatoes, avocados, onion, and cilantro in a large salad bowl.", "Toss with olive oil, lemon juice, salt, and pepper."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 224, Protein: 1.3g, Veggie carbs: 8.1g, Misc. Carbs: 5.6g, Fat: 10.6g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 36,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654821519/Screen_Shot_2022-06-09_at_6.38.19_PM_cygqhq.png",
    "recipeTitle": "Creamy No-Cheese Sauce",
    "servings": "4 servings",
    "ingredients": ["1 small, sweet potato, peeled and cubed", "1 cup finely chopped cauliflower florets or riced cauliflower", "2 1⁄2 cups water", "1⁄2 cup lite coconut milk from a can", "3 tbsp. nutritional yeast", "2 tsp lemon juice", "Pinch sea salt", "3⁄4 tsp garlic powder", "Pepper to taste"],
    "directions": ["Add potato, cauliflower, water, and salt to a pot. Bring to a low boil and cook for about 15 minutes, or until sweet potato is tender. Drain.", "Add to a blender with remaining ingredients and process until smooth.", "Use as a dip or sauce."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 77, Protein: 4g, Veggie carbs: 11g, Misc. Carbs: 8g, Fat: 2g",
    "mealType": ["Salads, Sauces & Sides", "Sauce"]
  },
  {
    "id": 37, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654821697/Screen_Shot_2022-06-09_at_6.41.08_PM_uorrxp.png",
   "recipeTitle": "Sunshine Bowl",
    "servings": "2 servings",
    "ingredients": ["Salad: Based on your desires. Select 3-6 of the following in 1⁄2 cup portions.", "Shredded Cabbage", "Arugula", "Lettuce", "Broccoli Slaw", "Broccoli", "Asparagus", "Zucchini", "Summer Squash", "Mushrooms", "Bell Pepper"],
    "directions": ["Chop your veggies and arrange into two bowls. Toss each with dressing and divide toppings among the two bowls."],
    "toppingTitle": "Toppings and Dressing", 
    "toppingIngredients": ["Topping: 1⁄2 small avocado, chopped", "Topping: 1 tbsp. slivered almonds", "Topping: 1 tbsp. hemp seed", "3 tbsp. natural, roasted almond butter", "2 tbsp. coconut milk", "1 tbsp. coconut aminos", "1 1⁄2 tsp rice vinegar", "Pinch garlic powder", "Pinch Stevia", "Pinch cayenne pepper"],
    "toppingDirections": ["Whisk dressing ingredients and place in refrigerator while you assemble the salad."],
    "nutritionDetails": "Note: the nutrition information is approximate, based on toppings. Calories: 352, Protein: 14.5g, Veggie carbs: 15g, Misc. Carbs: 10g, Fat: 25g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 38, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654821841/Screen_Shot_2022-06-09_at_6.43.41_PM_usvxqg.png",
    "recipeTitle": "Rainbow Salad",
    "servings": "3 servings",
    "ingredients": ["1 large, sweet potato, peeled and cubed", "1 medium red onion, thinly sliced", "Coconut oil cooking spray", "Pinch Sea Salt", "6 cups fresh spinach", "1 can black beans, drained and rinsed", "1 small avocado, chopped", "1⁄2 c pomegranate seeds"],
    "directions": ["Preheat oven to 425 F.", "Lay sweet potato cubes and onion on a nonstick baking sheet. Coat well with cooking spray and sprinkle lightly with seat salt.", "Roast for 20-22 minutes, or until potatoes are golden and tender and onions are caramelized.", "In a large bowl, add the spinach black beans and roasted sweet potatoes and onion. Toss with dressing. Top with avocado and pomegranate and serve."],
    "toppingTitle": "Dressing", 
    "toppingIngredients": ["1⁄2 c cilantro, chopped", "3 1⁄2 tbsp. lime juice", "1 tbsp. raw honey", "1 tbsp. coconut oil", "1⁄2 tsp cumin", "Sea Salt and pepper to taste"],
    "toppingDirections": ["Stir together the cilantro, lime juice, honey oil, cumin, salt, and pepper."],
    "nutritionDetails": "Calories: 392, Protein: 14g, Veggie carbs: 10g, Complex Carbs: 53g, Fat: 11.5g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
   },
  {
    "id": 39,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654822671/Screen_Shot_2022-06-09_at_6.57.24_PM_glyk2t.png",
    "recipeTitle": "BBQ Chicken Salad",
    "servings": "4 servings",
    "ingredients": ["2 boneless skinless chicken breasts, sliced into strips", "6 cups lettuce", "1 diced tomato", "1 bell pepper cut into small pieces", "1⁄2 avocado cut into cubes", "1⁄4 cup red onion, diced", "1⁄4 cup SF BBQ Sauce"],
    "directions": ["Place all ingredients for salad together in a large container.", "Mix all ingredients for dressing together, whisk briskly.", "When ready to eat salad, drizzle on dressing on top and enjoy!"],
    "toppingTitle": "Dressing", 
    "toppingIngredients": ["2 T Primal Kitchen Avocado mayo", "2 tbsp. coconut milk", "1⁄4 tsp. minced garlic", "1 tsp. fresh dill minced", "1 tsp. fresh chives minced", "1⁄4 tsp. paprika", "Sea salt and pepper"],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 170, Protein: 21.8g, Veggie carbs: 11.5g, Misc. Carbs: 1.3g, Fat: 4.8g",
    "mealType": ["Salads, Sauces & Sides", "Salad"]
  },
  {
    "id": 40, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654823207/broccoli-burritos-7_m6cba2.jpg",
    "recipeTitle": "Broccoli Burritos",
    "servings": "2 servings",
    "ingredients": ["2 broccoli stalks", "1 15 oz can garbanzo beans", "1⁄2 cup roasted red peppers", "2 tbsp tahini", "3 tbsp lemon juice", "4 cauliflower wraps", "6 tbsp or more of salsa"],
    "directions": ["Cut or break broccoli into florets. Peel stalks and cut into 1⁄2 inch rounds. Steam over boiling water until just barely tender. About 5 minutes.", "Drain garbanzo beans and place in a food processor with peppers, tahini, and lemon juice. Process until completely smooth, about 2 minutes.", "Spread about 1⁄4 of the garbanzo mixture on to the cauliflower wrap/tortilla and place in a large, heated skillet. Heat until tortilla is warm and soft. About 2 minutes. Arrange a line of cooked broccoli down the center, then sprinkle with salsa.", "Roll tortilla around the filling and repeat."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 317, Protein: 13g, Veggie carbs: 50g, Sugar: 4g, Fat: 9g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 41,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654823918/CauliflowerDirtyRice_sge7l1.jpg",
   "recipeTitle": "Cauliflower Dirty Rice",
    "servings": "6 servings",
    "ingredients": ["3 cups cauliflower, riced", "2 cups chicken stock or vegetable stock", "2-3 tablespoons coconut oil", "4 cloves garlic, minced", "1 cup white onion, diced", "2 celery stalks, chopped", "1 cup green pepper, diced", "1 cup red pepper, diced", "1 bunch scallions, chopped", "1 tsp. fresh thyme", "1 bay leaf", "1⁄2 tsp. Celtic sea salt", "1⁄2 tsp. pepper", "1⁄4 tsp. chili powder", "1⁄2 tsp. cumin"],
    "directions": ["Heat olive oil over medium heat in a large skillet", "Add garlic, onion, celery, peppers, and scallions, sauté until soft.", "Stir in riced cauliflower, adding thyme, bay leaf, salt, pepper, chili, and cumin.", "Add in the chicken stock (or vegetable stock)", "Allow to simmer over medium-low heat, stirring frequently, for 30 minutes or so or until liquid is cooked down."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 112, Protein: 4.7g, Veggie carbs: 16.5g, Fat: 5g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 42, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654915307/cauliflower-rice-stuffing_lpraea.png",
    "recipeTitle": "Cauliflower Rice Stuffing",
    "servings": "4 servings",
    "ingredients": ["1 1/2 tbsp coconut oil", "1 cup diced onion, about half a large onion", "1 cup chopped celery", "1 1/2 tbsp minced garlic", "6 cup cauliflower, cut into small, bite-sized florets", "2 tbsp fresh chopped parsley, minced, plus additional for garnish", "1 tsp poultry seasoning l/2 tsp ground sage", "1/2 tsp sea salt, plus more to taste black pepper", "1/2 cup low sodium chicken broth or vegetable broth"],
    "directions": ["Heat the coconut oil in a large frying pan on medium-high heat Add in the onion, celery, and garlic and cook, stirring frequently, until the onion is golden brown and tender. About 8 min.", "Reduce the heat to medium andstir in the cauliflower. Cookuntilthe cauliflower just begins to soften and brown, stirring frequently. About 10 min.", "Add in the parsley, poultry seasoning, sage, salt, and a pinch of pepper and cook 1 min.", "Stir in the broth,cover, andcook until the cauliflower is tender, and the liquid is absorbed. About 10 min.", "Season with salt, if needed. Garnish with additional parsley."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "No details available",
    "mealType": ["Vegetables"]
  },
  {
    "id": 43,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654915453/cauliflower-tortillas-sq_u8qe43.jpg",
    "recipeTitle": "Cauliflower Tortillas",
    "servings": "6 servings",
    "ingredients": ["3⁄4 a head of cauliflower riced or 2 cups riced and packed", "2 eggs", "Salt and pepper to taste"],
    "directions": ["Preheat oven to 375 degrees and line a baking tray with parchment paper.", "Toss 3⁄4 a head of cauliflower cut up and most of the stem removed and pulse until you get a texture slightly finer than rice.", "Place riced cauliflower in bowl and microwave for 2 minutes and stir, then another two minutes and stir again then place in a dish towel and squeeze excess water out as hard as you can.", "Place drained cauliflower back in bowl and add two eggs, salt and pepper and mix until well combined.", "Spread mixture onto a baking sheet into 6 small fairly flat circles.", "Place in the oven for 10 minutes then pull out of the oven and carefully peel them off the parchment and flip them and place back in the oven for 5-7 more minutes.", "Once they’re done place them on a wire rack to cool slightly.", "Heat a medium sized pan over medium heat and place the tortillas into the pan pressing down slightly and brown them to your liking."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 41, Protein: 5g, Veggie carbs: 4g, Fat: 1g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 44, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654915787/Cauliflower-pizza_wec4ah.png",
    "recipeTitle": "Cauliflower/No Flour Pizza",
    "servings": "3 servings",
    "ingredients": ["2 cups of grated cauliflower", "2 cups shredded mozzarella cheese (organic of course)", "2 eggs", "Optional: 1⁄2 cup sauteed onions."],
    "directions": ["Preheat the oven to 450 degrees.", "Grate 2 cups cauliflower", "Combine and mix 2 cups cauliflower, eggs, and cheese in a mixing bowl. This will be the crust of your pizza.", "Cut parchment paper to fit pizza pan. PARCHMENT PAPTER TRICK: Cut a circle of the right size, first tear off a square of parchment paper, roughly the size of the pan. Fold it in half and then fold it in half again. Next fold the square into the triangle. Find the corner of the triangle where the center of the paper will be, once It's unfolded. This is your center point.", "Hold the triangle up to the pan with the center point of the triangle at the middle of the pan. Approximate the distance from the middle of the pan to the outer edge and trim off the excess paper following the curve of the pan.", "Unfold the paper and lay it flat in the pan. Trim any rough edges if it doesn't fit quite right.", "Mix crust mixture thoroughly and spread on the parchment paper as thinly as possible.", "Cook the crust for 15 minutes. Let cool down for 5 minutes.", "Apply cheese and topping.", "Cook for an additional 10 minutes and enjoy!"],
    "toppingTitle": "Toppings", 
    "toppingIngredients": ["1⁄4 cup Organic Pizza Sauce (Primal Kitchen has good ones)", "1⁄2 cup Nutritional yeast to sprinkle on top (or little more mozzarella cheese)", "Sliced Mushrooms", "Basil Leaves", "Spinach", "Peppers", "Sliced Tomatoes", "Olives (optional)"],
    "toppingDirections": [],
    "nutritionDetails": "HAS DIARY,  EAT SPARINGLY,  JUST ONCE IN A WHILE AS A TREAT (1X PER MONTH MAX).",
    "mealType": ["Vegetables"]
  },
  {
    "id": 45, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654915964/Oregano-Rutabaga-Fries_oregj9.jpg",
    "recipeTitle": "Baked & Spicy Oregano Rutabaga Fries",
    "servings": "3 servings",
    "ingredients": ["4 turnips (rutabaga's) peeled and sliced into 1/2-inch French fries", "1 tbsp. coconut oil", "1/2 tbsp. chili powder", "1/2 tbsp. oregano"],
    "directions": ["Preheat the oven to 425 degrees.", "Put the sliced turnips in a mixing bowl and toss really well with the chili powder, oregano, and olive oil. Lay them out flat onto a lined and greased baking pan (I sprayed olive oil spray onto parchment paper.", "Bake 15 minutes, take the fries out and flip every one of them then bake for another 15 minutes on the other side.", "While the fries are baking, add the avocado, mayo, and lime juice to a food processor. Pulse until smooth."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 210.8, Protein: 3.6g, Veggie carbs: 21.8g, Fat: 14.1g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 46,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654916032/Pesto-Chicken-Spaghetti-Squash_hubfky.jpg",
    "recipeTitle": "Pesto Spaghetti Squash",
    "servings": "4 servings",
    "ingredients": ["1 spaghetti squash", "4 cups fresh parsley leaves", "4 cherry tomatoes", "3/4 cup chopped fresh chives", "3/4 cup coconut oil", "1/2 cup unsalted roasted almonds", "1/4 cup pine nuts", "Sea salt", "Fresh ground pepper", "Nutritional Yeast (instead of parmesan)"],
    "directions": ["Preheat oven to 425 F.", "Cut squash in half lengthwise and scoop out the seeds.", "Brush the inside flesh with olive oil and sprinkle with salt and pepper", "Place flesh side down and bake for 45 min until soft and tender.", "Place the pine nuts in a food processor and pulse until finely minced.", "Add parsley leaves, chives, oil, and process until smooth.", "Using a fork scrap out the spaghetti squash into a skillet.", "Add the pesto and stir until mixed thoroughly.", "Serve with halved cherry tomatoes and pine nuts for garnish.", "Enjoy!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 407.5, Protein: 3g, Veggie carbs: 12.25g, Misc. Carbs: 1.75g, Fat: 40.5g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 47, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654916316/Cauliflower-mashed_nrbard.png",
    "recipeTitle": "Mashed Potatoes oops, I mean Cauliflower",
    "servings": "4 servings",
    "ingredients": ["3 cups cauliflower (chopped)", "1 clove garlic", "1 cup cashews", "2 tbsp water", "1⁄2 tsp sea salt"],
    "directions": ["Place all mashed potato ingredients into a food processor.", "Process until creamy and smooth, similar in texture to the attached pictures. (Although you may be tempted to do so, do not add any other additional liquids other than the 2 tablespoons of water. Also, if it seems difficult to process at the beginning, you may need to stop and scrape the sides a few times to help get it started. Enjoy your RAW MASHED POTATOES"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 90, Protein: 4g, Veggie carbs: 20g, Misc. Carbs: 8g, Fat: 8g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 48, 
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654916787/Roasted-Cabbage_tlwohu.jpg",
    "recipeTitle": "Roasted Cabbage with Lime and Sriracha",
    "servings": "4 servings",
    "ingredients": ["1 medium-sized head of firm cabbage", "2 T olive or coconut oil", "2 T fresh squeezed lime juice", "2 tsp. Sriracha Sauce", "1/4 tsp. salt"],
    "directions": ["Preheat oven to 450F. Spray a baking sheet with non-stick spray or oil.", "Cut the cabbage into four pieces and remove any outer leaves. Cut each piece in half to make 8 wedges.", "Place each piece of cabbage on the baking sheet, arranging so the wedges are not touching each other. Whisk together the oil, lime juice, Sriracha Sauce, and salt to make the glazing mixture; then brush the mixture over the cabbage with a pastry brush. Carefully turn each piece of cabbage over and brush the other side, saving some liquid to brush again when you turn the cabbage after it's roasted on one side.", "Roast in the center of the oven for 15-17 minutes, or until the edges of the cabbage are starting to get brown. Carefully turn the hot cabbage pieces, and then brush again with the remaining lime-Sriracha-oil mixture.", "Roast for 15-17 minutes more, or until the second side is starting to brown. Remove from oven, place on serving dish."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 98.5, Protein: 2g, Veggie carbs: 6g, Misc Carbs: .5g, Fat: 7g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 49,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654917001/Roasted-Artichokes_yfkhrt.png",
    "recipeTitle": "Roasted Artichokes",
    "servings": "2 servings",
    "ingredients": ["1 can (14 oz) organic artichoke hearts, drained.", "2 garlic cloves, minced", "2 tbsp coconut oil", "1 tbsp nutritional yeast", "1⁄4 tsp sea salt", "Pinch black pepper"],
    "directions": ["Preheat oven to 425 F.", "Dry artichokes well with paper towels.", "To a bowl, add artichokes, garlic, oil, nutritional yeast, salt, and pepper.", "Toss well to coat.", "Lay onto a non-stick baking sheet and roast for about 18-20 minutes, tossing once after 10 minutes.", "You can use frozen artichokes that have been defrosted but thaw them and dry well. Cut large ones in half or quarters."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 178, Protein: 3.5g, Veggie carbs: 10g, Misc. Carbs: 6.5g, Fat: 14g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 50,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654917450/cauliflower-slaw_stlx0t.jpg",
    "recipeTitle": "Cauliflower Slaw",
    "servings": "4 servings",
    "ingredients": ["1 head of cauliflower steamed or boiled until tender, break or cut into bite size pieces.", "6 boiled eggs (when done peel eggs, rinse, and separate yokes into a bowl. Then mash the yolk and cut the whites into small bite size pieces then blend together).", "1/3 cup Primal Kitchen Avocado Mayo", "3 tbsp. of mustard", "3 tbsp. of pickle relish", "1/8 cup of chopped onion", "Salt/pepper to taste"],
    "directions": ["Mix all together and you can garnish with egg slices and parsley.", "Chill overnight"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 144, Protein: 12g, Veggie carbs: 8.25g, Fat: 6g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 51,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654917604/Roast-Brussel-Sprouts-with-Lemon-and-Parsley_mj6mzo.jpg",
    "recipeTitle": "Crispy Brussel Sprouts with Lemon",
    "servings": "4 servings",
    "ingredients": ["1 lb. Brussel sprouts", "1⁄2 cup avocado oil", "1 lemon, juice, and zest", "Salt and pepper", "2/5-3/4 cup spicy almond & seed mix or your own choice of nuts and seeds"],
    "directions": ["Trim and rinse the Brussel sprouts. Coarsely shred in a food processor or with a sharp knife. Place in a salad bowl.", "Mix olive oil, lemon juice/zest and salt and pepper. Pour over the Brussel sprouts.", "Let marinate for 10 minutes. Then add the spicy almond and seed mix immediately prior to serving.", "This vegetable salad as a side dish to meat, fish, or a simple omelet. SPICY ALMOND AND SEE MIX", "Heat the oil in a large frying pan and add the chili first.", "Add almonds and seeds. Stir thoroughly.", "Salt and sauté for a few minutes more but pay close attention as almonds and seeds are very heat sensitive. The oil should not be hot enough for the spice flavors to develop, but the almonds and seeds should not be burned.", "Let cool and sprinkle over the salad before serving."],
    "toppingTitle": "Spicy Almond and Seed Mix", 
    "toppingIngredients": ["1 tbsp. coconut oil or olive oil", "2 oz. almonds", "1 oz. pumpkin seeds", "1 oz. sunflower seeds", "1⁄2 tsp ground cumin or crushed fennel seeds", "1 tsp chili paste", "1 pinch salt"],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 484, Protein: 11g, Veggie carbs: 15g, Misc. Carbs: 6g, Fat: 45g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 52,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1654918268/mashed-parsnips_pvsi0a.jpg",
    "recipeTitle": "Garlic Mashed Parsnips",
    "servings": "4 servings",
    "ingredients": ["2 lbs. parsnips, peeled", "6 garlic cloves, peeled", "1/4 cup coconut milk", "2 tbsp. coconut oil", "1 tbsp. water", "1 tsp. sea salt", "Salt/pepper to taste"],
    "directions": ["Peel parsnips, garlic and then slice.", "Combine parsnips, garlic, and water into a slow cooker.", "Add coconut oil over the ingredients and salt and pepper to taste.", "Cook on high for 3-4 hours.", "Once tender and cooked mash together with coconut milk", "Serve and Enjoy!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 231, Protein: 2.75g, Veggie carbs: 40.8g, Fat: 7.8g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 53,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655238159/Broccoli_Pesto_Pasta_wiadt4.png",
    "recipeTitle": "Broccoli Pesto Pasta",
    "servings": "4 servings",
    "ingredients": ["2 cups broccoli florets", "2 cups basil leaves", "1⁄2 cup dry roasted macadamia nuts", "3 tbsp nutritional yeast", "2 tbsp. avocado oil", "3 tbsp. water", "1 1⁄2 tbsp lemon juice", "2 cloves garlic", "1⁄2 shallot, chopped", "1⁄2 teaspoon seat salt", "1⁄4 tsp pepper", "4 bags Miracle Noodles, drain and rinsed (or substitute zucchini noodles)"],
    "directions": ["Steam the broccoli in a steamer basket until tender (about 5 minutes).", "Add broccoli and remaining ingredients (except noodles) to a large food processor or process until thick and smooth.", "Add noodles to a pot and heat over medium for 1 minute.", "Divide among four plates and serve."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 216, Protein: 5g, Complex carbs: 9g, Misc. Carbs: 4g, Fat: 19.5g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 54,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655238411/orangebrussels_is550t.jpg",
    "recipeTitle": "Peppery Orange Brussel Sprouts",
    "servings": "5 servings",
    "ingredients": ["2 lb. Brussel sprouts, quartered", "1 medium sweet onion, thinly sliced", "Zest and juice of one orange", "1 tbsp. butter", "1 tbsp. ground black pepper", "A dash of salt to taste"],
    "directions": ["Heat a large skillet (preferably cast iron) over medium-high heat.", "Place Brussel sprouts and onions in skillet and cook for 5 minutes (until they just start to brown)", "Add juice and zest and cook for an additional 5 minutes (I stir more frequently in the second five minutes to keep them from burning", "Add pepper and salt.", "Stir well and serve!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 123, Protein: 6.4g, Veggie carbs: 20.4g, Fat: 4g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 55,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655238517/Academy_Mac_luhp4d.png",
    "recipeTitle": "Academy Mac & Cheese",
    "servings": "2 servings",
    "ingredients": ["1 butternut squash (about 12 ounces)", "2 medium heads broccoli", "2 1⁄2 cups uncooked Veggiecraft Farms Elbow Cauliflower Pasta", "4 cloves garlic", "1⁄2 cup almond or coconut milk", "3 tablespoons nutritional yeast", "Sea salt", "1 tablespoon (or less) garlic powder", "Parsley flakes Freshly ground black", "Pepper"],
    "directions": ["Bake the butternut squash whole and unpeeled in the oven at 350oF for exactly 30 minutes. Overbaking may cause problems with the preparation later.", "Separate the broccoli into small florets, then peel the stems and cut them into small pieces.", "Boil the pasta according to the package instructions, being careful not to overcook it.", "Peel the cooked squash, then cut it in half lengthwise, spoon out the seeds, and cut it into smaller chunks.", "Place a steamer basket insert in a saucepan filled with about 2 inches of water. Bring to a simmer over high heat, then reduce the heat to medium-low and add the squash chunks and garlic cloves.", "Cover the pan and steam until tender, about 10 minutes.", "Place the broccoli stem pieces in a separate larger pot with a bit of water, cover, and steam for 5 minutes. Then add the broccoli florets, cover the pan, and continue steaming for 3 to 4 minutes. Drain the water.", "Drain the water from the butternut squash and remove the pan from the flame. Add the plant milk, nutritional yeast, garlic powder, and salt to taste, and blend well with an immersion blender (or in a regular blender) until the mixture is smooth and creamy. Add the parsley flakes and season with pepper to taste and stir with a spoon.", "Bring the sauce to a very low simmer, then add the pasta and broccoli and stir very gently with a wooden spoon"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 260.5, Protein: 16.25g, Complex Carbs: 20g, Sugar: 1g, Veggie carbs: 24g, Fat: 1g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 56,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655238735/Roasted_Veggies_jgelrh.png",
    "recipeTitle": "Roasted Veggies",
    "servings": "4 servings",
    "ingredients": ["1 cup zucchini chopped", "1 cup yellow squash chopped", "1 cup red or white onion (or both) chopped", "1 cup asparagus chopped", "1 cup carrots chopped", "1 cup cauliflower chopped", "4 tbsp. coconut oil", "1 tsp. oregano", "4 cloves garlic minced", "Salt and pepper to taste"],
    "directions": ["Preheat oven to 450 degrees.", "In a large bowl combine all ingredients together", "Spread vegetables evenly on a large baking sheet.", "Cook for 60 minutes until vegetables are crispy."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 170.75, Protein: 2.5g, Veggie carbs: 11.75g, Fat: 14g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 57,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655244668/Mexican-Zucchini_uwwzun.webp",
    "recipeTitle": "Skillet Mexican Zucchini",
    "servings": "4 servings",
    "ingredients": ["1 garlic clove, finely chopped", "1 tbsp. organic butter", "1 lb. zucchini, diced", "1 large tomato, cored, seeded and diced", "1 green onion, thinly sliced", "1 tbsp. minced fresh cilantro or cilantro paste", "1 tsp. minced pickled jalapeño", "Fresh lime juice, to taste", "Salt, to taste", "Freshly ground black pepper, to taste"],
    "directions": ["Cook the garlic in butter in a large skillet over medium heat 1 minute, stirring until sizzling.", "Add zucchini and cook stirring occasionally, about 3 minutes or until slightly softened.", "Add the tomato and green onion and cook about 3 minutes.", "Remove skillet from heat and add cilantro paste, jalapeño, and lime juice.", "Season with salt and pepper to taste."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 102, Protein: 5g, Veggie carbs: 8g, Fat: 6g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 58,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655244753/Spiced_Coconut_Spinach_yeyyvc.jpg",
    "recipeTitle": "Spiced Coconut Spinach",
    "servings": "2 servings",
    "ingredients": ["1 shallot", "1 large clove of garlic", "1/4 tsp. sea salt", "1 tablespoon organic butter", "1/4 tsp. yellow mustard seeds", "1/4 tsp. whole cumin seeds", "1/4 tsp. red pepper flakes", "1 cup finely sliced asparagus - optional", "7 oz. spinach, well washed, and chopped", "Squeeze of lemon", "1 1/2 tablespoons unsweetened coconut, lightly toasted"],
    "directions": ["Place the shallot and garlic on a cutting board, sprinkle with the salt, and chop/mash everything into a paste.", "Heat the oil in your largest skillet over medium heat. Add the seeds, cover with a lid, and let them toast a bit.", "Remove the lid, stir in the red pepper flakes, and let cook for a minute. Stir in the asparagus if you're using it, let cook roughly another minute, then stir in the garlic- shallot paste and all of the spinach.", "Keep stirring until the spinach starts breaking down a bit (about a minute). Finish with a bit of fresh lemon juice and the coconut."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 108.5, Protein: 3.5g, Veggie carbs: 7g, Misc Carbs: 1.5g, Fat: 10g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 59,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655244967/Crispy-Baked-Sweet-Potato-Fries_j7wsuo.jpg",
    "recipeTitle": "Spicy Sweet Potato Fries with Avocado Garlic Dipping Sauce",
    "servings": "2 servings",
    "ingredients": ["2 Large Sweet Potatoes", "2 Tbsp. Sriracha (can add more if you like it SPICY!)", "1/2 Tsp. Salt", "1/4 Cup Coconut Flour (or Almond Flour)", "2 Tbsp. Coconut Oil"],
    "directions": ["Pre-heat your oven to 450F.", "Cut your sweet potatoes into fries and place in a bowl.", "Melt your coconut oil and pour over fries coating all evenly.", "Next, stir in your sriracha and coat your fries evenly.", "Throw in the flour and salt coating the fries evenly.", "On a parchment-lined baking sheet evenly single layer fries and place in the oven for 20 minutes.", "Just before the fries are done place all avocado mayo ingredients into your food processor and blend until smooth. Serve with sweet potato fries.", "Remove sweet potato fries from the oven and enjoy with the avocado “mayo”."],
    "toppingTitle": "Avocado “Mayo” Dip", 
    "toppingIngredients": ["2 Avocados (peeled and pitted)", "1 Tsp. Finely chopped fresh garlic or garlic paste", "1/3 Tsp. Sea Salt", "1 Tbsp. Fresh Squeezed Lemon Juice"],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 501, Protein: 20g, Complex carbs: 51g, Misc. Carbs: 11g, Fat: 26g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 60,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655245049/Buffalo_Cauliflower_tots_cigeau.jpg",
    "recipeTitle": "Buffalo Cauliflower Tots",
    "servings": "4 servings",
    "ingredients": ["1 head of cauliflower", "Batter ingredient: 1 cup Almond Milk", "Batter ingredient: 3⁄4 cup coconut Flour", "Batter ingredient: 1 tsp. onion powder", "Batter ingredient: 1 tsp garlic powder", "Batter ingredient: 1⁄2 tsp salt", "Batter ingredient: 1⁄4 tsp paprika", "Batter ingredient: 1/8 tsp ground pepper"],
    "directions": ["Preheat the oven to 450 degrees", "Wash and cut the cauliflower head into bite size pieces or florets", "Mix the batter ingredients in a bowl until well combined,", "Dip each floret into the batter and coat evenly. Shake off excess and place on a parchment lined baking sheet.", "Bake for 20 minutes, flipping the florets over halfway through.", "To make the Buffalo wings sauce you can mix all the ingredients in a bowl or add them to a blender and blend until smooth. Then pour the sauce into a mixing bowl, I prefer to blend them, but it’s up to you.", "Toss the baked florets into the sauces, 1 or 2 pieces at a time. Shake off excess and place back on baking sheet.", "Bake for another 20 minutes or until golden brown, flipping the florets over halfway through.", "Serve with avocado dip or organic sugar free ranch dressing and some chopped chives on top (optional).", "Keep the buffalo cauliflower tots in a sealed container in the fridge for up to 3 days."],
    "toppingTitle": "Buffalo Sauce", 
    "toppingIngredients": ["1⁄2 c water", "1⁄4 c apple cider vinegar (4 tbsp)", "1⁄4 c Organic tomato paste (4 tbsp)", "2 tbsp tamari or coconut aminos", "2 tbsp tahini", "2 tsp paprika", "2 tsp garlic powder", "1⁄2 tsp cayenne powder"],
    "toppingDirections": [],
    "nutritionDetails": "No details available",
    "mealType": ["Vegetables"]
  },
  {
    "id": 61,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655245155/Butternut_curry_sqxk0k.png",
    "recipeTitle": "Butternut Curry",
    "servings": "4 servings",
    "ingredients": ["2 cups spinach", "2 cups prepared cauliflower rice", "1⁄2 c cilantro, chopped", "1⁄4 cup roasted cashews, chopped", "3 cups butternut squash, cubed", "1 tbsp. coconut oil", "2 medium shallots", "1 can lite coconut milk", "1⁄2 cup vegetable or chicken broth", "1 1⁄2 cups garbanzo beans, drained and rinsed", "1 1⁄2 tbsp. curry powder", "1 tbsp. fresh ginger (or 1 tsp powdered ginger)", "1 tsp turmeric powder", "1/2 tsp cinnamon", "1⁄2 tsp smoked paprika", "Pinch stevia", "1⁄2 tsp sea salt and pepper"],
    "directions": ["Heat oil in a large pan. Add shallots and cook for 4 minutes. Add squash and sauté for 3-4 minutes.", "Add coconut milk, broth, garbanzo beans, curry powder, ginger, turmeric, cinnamon, paprika, stevia and salt and pepper. Stir well, then simmer until the sauce is reduced by half and squash is fork-tender (about 10-12 minutes.)", "Add any other veggies you want, rice vinegar, and stir fry for another 1-2 minutes.", "In place of rice, you can serve over cauliflower rice or zoodles."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 452, Protein: 10.5g, Veggie carbs: 50g, Misc. Carbs: 10g, Fat: 16g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 62,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655245557/Healthy-Fried-Rice_lqup1w.jpg",
    "recipeTitle": "Veggie Fried Rice",
    "servings": "6 servings",
    "ingredients": ["2 tablespoons sesame oil, divided", "2 cloves garlic, minced", "1 1-inch piece fresh ginger, grated", "3 eggs", "4 cups brown rice (cooked & cooled)", "1 cup frozen corn", "1-2 cups frozen peas", "1⁄2 tablespoon rice vinegar", "2-3 tablespoons liquid Aminos", "Fresh chives, fresh basil, baby spinach, any other add ins you want!"],
    "directions": ["Heat one tablespoon oil in a large pan over medium heat. Add the garlic cloves and ginger and stir fry for one minute. Crack the eggs directly into the pan and use your spatula to gently move around in the pan until barely cooked, 1-2 minutes.", "Add the rice and stir fry for a few minutes, adding the other tablespoon of oil and turning the heat up. The eggs should sort of incorporate and stick to the rice.", "Add the frozen corn, peas, rice vinegar, and soy sauce and stir fry for another 1-2 minutes.", "Remove from heat, stir in any additional add-ins, and serve!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 271.7, Protein: 8.5g, Complex Carbs: 30.7, Veggie carbs: 7.7g, Misc carbs: 2.7g, Fat: 6.8g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 63,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655245644/Broccoli-Fritters_tl3msj.jpg",
    "recipeTitle": "Broccoli Fritters",
    "servings": "6 servings",
    "ingredients": ["1 Cup steamed broccoli", "2 Eggs", "1/2 tsp curry powder", "1⁄4 tsp sea salt and pepper to taste", "Coconut oil", "*Coconut Flour (may need a little coconut flour)"],
    "directions": ["In a food processor, pulse the broccoli until finely ground.", "Pulse eggs, curry powder, salt, and pepper. The batter should be thick enough to hold a pancake shape in the pan. If it's too watery, add coconut flour (1 tsp) and blend again.", "Heat skillet to medium-high. I love cast iron. Always fully heat the cast iron first and add oil. Drop about 2 tbsp. of 'batter' into the hot pan for each fritter.", "Brown on one side before turning. You can peek under to see if it's ready. Flip and brown other side. Enjoy!"],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 327, Protein: 16.3g, Veggie carbs: 11.2g, Misc. Carbs: 1.1g, Fat: 40.7g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 64,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655245709/Zucchini-Falafel.jpeg_bscqlg.jpg",
    "recipeTitle": "Zucchini Falafel",
    "servings": "4 servings",
    "ingredients": ["2 cups zucchini (grated)", "2 cups canned chickpeas", "2 garlic cloves", "2 cups cilantro", "1 tsp. chili powder", "1 tsp. cumin powder", "1 tsp. coriander powder", "1/2 tsp. salt (to taste)"],
    "directions": ["Grate the zucchini and add 1/2 tsp. salt and allow to rest for 30 minutes. Next squeeze the zucchini to remove as much moisture as possible.", "Chop coriander leaves and garlic. Grind the cooked chickpeas using very little water.", "To the squeezed zucchini add the chickpea puree, coriander leaves + garlic mixture, chili powder, coriander powder, cumin powder and salt. Mix well.", "Make small balls and flatten, place on a greased baking sheet, and bake in a preheated 400F oven for 20 min, flip over and then bake for another 10 - 15 minutes."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 166.5, Protein: 6g, Complex Carbs: 5.25g, Veggie carbs: .25g, Misc. Carbs: 11g, Fat: 9.25g",
    "mealType": ["Vegetables"]
  },
  {
    "id": 65,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655246005/Sauteed_Peppers_tpsfpt.png",
    "recipeTitle": "Sauteed Peppers",
    "servings": "1 serving",
    "ingredients": ["3 Red Peppers", "1 Yellow Pepper", "1 Yellow Onion", "2 Small Yukon Gold Potatoes or 2 cups cut up cauliflower", "2 T of Avocado Oil", "Salt and Pepper to taste", "Optional: Red Chili Flakes"],
    "directions": ["Wash the peppers, dry, and core, cut into slices.", "Dice up 1 Yellow Onion.", "Slice 2 small Yukon Gold Potatoes (you may substitute with any type of potato or butternut squash or yams)", "Turn your burner onto medium low.", "Add the avocado oil to your skillet.", "Place the onions in the skillet and allow the onion to become a little translucent.", "Add the peppers.", "Cook for about 5 minutes in the skillet.", "Add the potatoes or cauliflower.", "Stirring occasionally.", "Cook all ingredients covered on the stove. You will require the steam from the vegetable to help with the cooking time.", "Cook for approx. 15-20 mins.", "When ready to service add the salt and pepper at the last minute.", "Optional to add Red Chili flakes", "TIP: YOU CAN USE CAULIFLOWER INSTEAD OF RED POTATOS, OR JUST LEAVE THE POTATOS OUT, IF YOU ARE DOING A LOW CARB DAY."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "No details available",
    "mealType": ["Vegetables"]
  },
  {
    "id": 66,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655246116/Honey_Dijon_Brussels_rl03td.png",
    "recipeTitle": "Honey Dijon Brussels",
    "servings": "4 servings",
    "ingredients": ["4 cups Brussel Sprouts, trimmed and halved", "1 tbsp. ghee", "1 tbsp. avocado oil", "1 1⁄2 tbsp. Dijon mustard", "15 drops of stevia (15 drops=1 tbsp)", "Pinch sea salt and pepper"],
    "directions": ["In a medium pan, add ghee and oil over medium heat.", "Add Brussel sprouts and sauté for 5 minutes.", "Stir in mustard and honey and coat well.", "Cook 1 minute, or until nicely browned and slightly tender.Season with salt and pepper and serve."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 128, Protein: 3.5g, Veggie carbs: 12g, Misc. carbs: 5g, Fat: 7g",
    "mealType": ["Vegetables"]
  },  
  {
    "id": 67,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655246299/Keto-Avocado-Hummus_buxysg.jpg",
    "recipeTitle": "Keto Avocado Hummus",
    "servings": "4 servings",
    "ingredients": ["1/2 tsp. Garlic Powder", "1 dash Salt", "1 head, large Cauliflower", "1/2 cup Water", "1 cup Greek Style Nonfat Yogurt - Plain", "2 tbsp. Buffalo Style Wing Sauce", "1 tbsp. I Can't Believe It's Not Butter!", "1/3 cup Bob's Red Mill Whole Grain Oat Flour", "1 cup Almond Milk - Unsweetened Original"],
    "directions": ["Preheat oven to 450F.", "Whisk together Greek yogurt, milk, water, garlic powder and oat flour until well combined. It may be thick.", "Toss cauliflower florets in yogurt mixture until well coated.", "Place cauliflower on baking sheet lined with foil and sprayed.", "Bake for 12-15 minutes, until coating bakes over florets.", "Combine buffalo wing sauce, butter, and salt.", "Pour sauce over cauliflower pieces and toss on the baking sheet to coat thoroughly.", "Bake for another 5-8 minutes."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 154.5, Protein: 8.25g, Complex Carbs: 6.5g, Veggie carbs: 2.5g, Misc. carbs: 9.75g, Fat: 5.25g",
    "mealType": ["Vegetables"]
  },  
  {
    "id": 68,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655246423/Crispy_Broccoli_rtpj2r.png",
    "recipeTitle": "Crispy Broccoli",
    "servings": "4 servings",
    "ingredients": ["2 tbsp. butter", "5 cloves garlic, sliced think", "Pink crushed red pepper flakes", "3 cups broccoli florets", "1 tbsp. coconut aminos", "1 tsp toasted sesame seeds", "Pinch garlic salt"],
    "directions": ["In a medium pan, add sesame oil and heat over medium. Once hot, add garlic and red pepper and sauté for 30 seconds.", "Add in broccoli and stir for 4 minutes.", "Add coconut aminos and cook for 1 more minute or until broccoli is tender."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 154.5, Protein: 8.25g, Complex Carbs: 6.5g,Veggie carbs: 2.5g, Misc. carbs: 9.75g, Fat: 5.25g",
    "mealType": ["Vegetables"]
  },  
  {
    "id": 69,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655246629/Garbanzo_Crunchies_Healthy_Croutons_dy8f47.png",
    "recipeTitle": "Garbanzo Crunchies/Healthy Croutons",
    "servings": "4 servings",
    "ingredients": ["2 cans (15 oz) Garbanzo Beans", "Garlic Salt", "Onion Powder", "Sea Salt", "Pepper Flakes"],
    "directions": ["Drain the garbanzo beans and put into a bowl.", "Sprinkle with garlic salt, sea salt, onion powder and pepper flakes.", "Pour mixture into air fryer.", "Fry at 400 degrees for 30 minutes. Shake every 5-7 minutes."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 197, Protein: 11g, Complex carbs: 30g, Fat: 4.3g",
    "mealType": ["Vegetables"]
  },  
  {
    "id": 70,
    "image": "https://res.cloudinary.com/dky0teawd/image/upload/v1655246741/Onion_Rings_y6gnk0.png",
    "recipeTitle": "Onion Rings",
    "servings": "4 servings",
    "ingredients": ["1 large yellow onion sliced into 1⁄4” rounds (Vidalia, white or red)", "4 tbsp. coconut flour", "6 tbsp. nutritional yeast", "1 pinch salt to taste", "1 tsp garlic powder", "1 pinch ground black pepper", "2 eggs", "1 cup coconut oil, refined if you don't love the coconut flavor", "salt to taste"],
    "directions": ["Heat the coconut oil in a large pan, over medium low heat.", "While the oil heats, whisk the eggs together with 1/3 oz. (about 1.5 tbsp) coconut flour and a pinch of salt. Whisk until the ingredients are blended.", "Combine the rest of the dry ingredients in another medium sized bowl.", "Using a fork, completely coat each onion ring with the beaten egg, and then lift and drop the coated onion ring into the flour mixture. Spoon the flour mix over the entire ring, and gently move the rings to a plate.", "Add some rings to the pan, leaving space in between each ring. Fry for about 3-4 minutes per side, until golden brown, and then remove to a plate lined with paper towels to cool. Continue this process until done, and then salt to taste.", "Tip: I found using my fingers to dip the onion in the batter and mixture worked best. Using a fork, versus tongs or a spatula is an easy and gentle way to flip the onion ring without disrupting the coating. You can fry in tallow, or other fat with a high heat point if you don't like coconut oil.", "Tip 2: The batter may be quite thick and stiff, so thin it with either cream or water to a pancake-like batter consistency. Then dip the onion rings in this, placing gently into the low-moderate heated oil. I also added some coconut flakes to the dry mixture. Nice add."],
    "toppingTitle": "", 
    "toppingIngredients": [],
    "toppingDirections": [],
    "nutritionDetails": "Calories: 216, Protein: 13g, Fat: 19g",
    "mealType": ["Vegetables"]
  },  
]
module.exports = recipeData;